n = int(input('Digite um número inteiro:'))
print('___________')
print('{} x {} = {}'.format(n, 0, n*0))
print('{} x {} = {}'.format(n, 1, n * 1))
print('{} x {} = {}'.format(n, 2, n * 2))
print('{} x {} = {}'.format(n, 3, n * 3))
print('{} x {} = {}'.format(n, 4, n*4))
print('{} x {} = {}'.format(n, 5, n*5))
print('{} x {} = {}'.format(n, 6, n*6))
print('{} x {} = {}'.format(n, 7, n*7))
print('{} x {} = {}'.format(n, 8, n*8))
print('{} x {} = {}'.format(n, 8, n*8))
print('{} x {} = {}'.format(n, 9, n*9))
print('___________')
print('{} / {} = {}'.format(n, 1, n/1))
print('{} / {} = {}'. format(n, 2, n/2))
print('{} / {} = {}'.format(n, 3, n/3))
print('{} / {} = {}'.format(n, 4, n/4))
print('{} / {} = {}'.format(n, 5, n/5))
print('{} / {} = {}'.format(n, 6, n/6))
print('{} / {} = {}'.format(n, 7, n/7))
print('{} / {} = {}'.format(n, 8, n/8))
print('{} / {} = {}'.format(n, 9, n/9))
print('___________')
